server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:sportapp
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: l9Hlc0nMwOBcLIMT5haVcshwniUj1677CzOXywqozbgWcbCEg9P7ZP680iJIooIl
  expiration: 86400000

app:
  superadmin:
    email: ${APP_SUPERADMIN_EMAIL:}
  security:
    cors:
      allowed-origin-patterns:
        - "http://localhost:*"


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
